apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: queue
scopes:
  - producer
  - consumer
spec:
  type: pubsub.queue
  version: v1
  initTimeout: 1m
  metadata: 
  - name: host
    value: "nil"