apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  labels:
    app: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
      annotations:
        dapr.io/unix-domain-socket-path: "/tmp/dapr-components-sockets"
        dapr.io/app-id: "queue"
        dapr.io/enabled: "true"
        dapr.io/log-level: "debug"
        dapr.io/sidecar-liveness-probe-delay-seconds: "45"
        dapr.io/sidecar-readiness-probe-delay-seconds: "45"
        dapr.io/sidecar-liveness-probe-threshold: "5"
        dapr.io/sidecar-readiness-probe-threshold: "5"
    spec:
      volumes:
        - name: dapr-unix-domain-socket
          emptyDir: {}
      containers:
        - name: component
          volumeMounts:
            - name: dapr-unix-domain-socket
              mountPath: /tmp/dapr-components-sockets
          image: brycehuang/pubsub:v3
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh","-c","sleep 30"]
          env:
            - name: TZ
              value: Asia/Shanghai
